site_name: RingaJS Documentation
pages:
    - Home: index.md
    - 'Why Ringa?': whyRinga.md
    - Overview: overview.md
    - Model: model.md
    - Controllers: controller.md
    - Executors: executors.md