site_name: Ringa JS
site_description: Ringa JS is a scalable framework for your small or enterprise-level Javascript project.
site_author: Joshua Jung
copyright: © 2017 Joshua Jung and the Ringa JS Team
google_analytics: ['UA-108440815-1', 'ringajs.com']
theme_dir: cinder
pages:
    - Home: index.md
    - Get Started:
        - Live Demo: gettingStarted/demo.md
        - Hello World Tutorial: gettingStarted/helloWorld.md
        - Code Examples: gettingStarted/examples.md
    - Architecture:
        - Lifecycle: architecture/lifecycle.md
        - Event System: architecture/events.md
        - Dependency Injection: architecture/dependencyInjection.md
        - Debugging: architecture/debugging.md
        - Building Component Libraries: architecture/buildingComponentLibraries.md
    - Plugins:
        - react-ringa: plugins/reactRinga.md
        - Inspector: plugins/inspector.md
    - Docs:
        - Index: docs/index.md
        - RingaObject: docs/ringaObject.md
        - RingaEvent: docs/ringaEvent.md
        - Model: docs/model.md
        - Controller: docs/controller.md
        - Executors: docs/executors.md
        - React Ringa: docs/reactRinga.md
    - Components:
        - Introduction: reactLibrary/introduction.md
        - Core: reactLibrary/core.md
        - Overlays: reactLibrary/overlays.md
        - Modals: reactLibrary/modals.md
        - Drag and Drop: reactLibrary/dragDrop.md
    - Links: links.md
extra_css: [extra.css]
repo_url: https://github.com/joshjung/ringa
include_next_prev: false
