site_name: RingaJS
theme_dir: cinder
pages:
    - Home: index.md
    - Why Ringa: whyRinga.md
    - Demo: demo.md
    - Hello World: helloWorld.md
    - Model: model.md
extra_css: [extra.css]
repo_url: https://github.com/joshjung/ringa
include_next_prev: false
